#!/usr/bin/env bash

if [[ $# -gt 0 && ${GITHUB_ACTIONS} -eq true ]]; then
    export GHOST_HOSTED_URL=${INPUT_GHOST_HOSTED_URL}
    export GHOST_STATIC_HOST_URL=${INPUT_GHOST_STATIC_HOST_URL}
    export CUSTOM_REPLACE_KEYS=${INPUT_CUSTOM_REPLACE_KEYS}
    export CUSTOM_REPLACE_VALUES=${INPUT_CUSTOM_REPLACE_VALUES}
    export ROOT_INDEX_JSONLD=${INPUT_ROOT_INDEX_JSONLD}
    export BREADCRUMB_ROOT_INDEX_JSONLD=${INPUT_BREADCRUMB_ROOT_INDEX_JSONLD}
    export S3_BUCKET_NAME=${INPUT_S3_BUCKET_NAME}
    export AWS_ACCESS_KEY_ID=${INPUT_AWS_ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${INPUT_AWS_SECRET_ACCESS_KEY}
    export AWS_DEFAULT_REGION=${INPUT_AWS_REGION}
fi

/src/run.sh
